sudo: required

language: python

services:
  - docker

env:
  - POSTGIS_USER="postgres"
    POSTGIS_PASS="mysecretpassword"
    POSTGIS_PORT=5435
    POSTGIS_DB="tds_tests"
    POSTGIS_URL="postgresql://$POSTGIS_USER:$POSTGIS_PASS@172.17.0.1:$POSTGIS_PORT/$POSTGIS_DB"
    POSTGIS_PUBLIC_URL="postgresql://$POSTGIS_USER:$POSTGIS_PASS@127.0.0.1:$POSTGIS_PORT/$POSTGIS_DB"
    GEOSERVER_ENDPOINT="http://127.0.0.1:8181/geoserver/rest/"
    GEOSERVER_USERNAME="admin"
    GEOSERVER_PASSWORD="geoserver"
    CKAN_USERNAME="tethys"
    CKAN_PASSWORD="password"
    CKAN_APIKEY="826650aa-d551-4abc-8d06-180e17ea9e93"
    CKAN_ENDPOINT="http://127.0.0.1:5000/api/3/action/"

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

stages:
  - lint
  - test
  - ckan_e2e_tests_py3
  - geoserver_e2e_tests_py3
  - name: deploy-pip
    if: tag =~ ^\d+\.\d+\.\d+$
  - name: deploy-conda
    if: tag =~ ^\d+\.\d+\.\d+$

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Create environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  # Install Python 3 compatible version of gsconfig
  - conda install -c tethysplatform gsconfig
  # Install dependencies
  - pip install -r requirements.txt;
  - pip install python-coveralls
  - python setup.py develop

script:
  - . travis/run_unit_tests.sh

after_success:
    - coveralls

jobs:
  include:
    - stage: lint
      python: "3.6"
      install:
        - pip install flake8
      script:
        - flake8

    - stage: geoserver_e2e_tests_py3
      python: "3.6"
      before_install:
        - . travis/setup_geoserver_e2e_tests.sh
      script:
        - . travis/run_geoserver_e2e_tests.sh

    - stage: ckan_e2e_tests_py3
      python: "3.6"
      before_install:
        - . travis/setup_ckan_e2e_tests.sh
      script:
        - . travis/run_ckan_e2e_tests.sh

    - stage: deploy-pip
      script:
        - echo "deploying to pip..."

    - stage: deploy-conda
      script:
        - echo "deploying to conda..."
