name: test
on:
  push:
  pull_request:
  # schedule:
  #   - cron: "0 8 * * *"

jobs:
  test:
    name: Test Python ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          - Windows
          - MacOs
        py:
          # - "3.10.0-rc.1"
          - "3.9"
          # - "3.8"
          # - "3.7"
          # - "3.6"
    steps:
      - name: Setup Python ${{ matrix.py }} for test
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v2
      - name: Install TDS
        run: python -m pip install .
      - name: Install Test Dependencies
        run: python -m pip install .[tests]
      - name: Install tox-gh
        run: python -m pip install tox-gh
      - name: Setup test suite
        run: tox r -vv --notest
      - name: Run unit tests
        run: tox r --skip-pkg-install
        # env:
        #   PYTEST_ADDOPTS: "-vv --durations=10"