name: Unit Tests
on:
  push:
  pull_request:
  # schedule:
  #   - cron: "0 8 * * *"

jobs:
  test:
    name: Test Python ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          - Windows
          - MacOs
        py:
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.py }} for test
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install tox tox-gh-actions
      - name: Run tests
        run: tox
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
